### ISSUE TITLE
version 7

### ISSUE THREAD

**Issue by ghost** [mccrodp/message_private#25]
Hi,

what happened to the Drupal 7 version of this module?

https://www.drupal.org/project/message_private used to list the module for D7 but looks like the project was deleted and recreated again? what is the gain here? Or planning a backport based on latest development? At least few people including me were using the module and it was helpful and the dependency seems the similar.

**Comment by NewZeal** [comment]
Nothing happened to the Drupal 7 version of this module.  It never existed.  It is impossible to delete a project on Drupal.  The message_private module was started on 30 Dec 2016.

**Comment by ghost** [comment]
@NewZeal better ask Paul ( @mccrodp ) as he was the maintainer of D7 module as well. I've personally used this module for Drupal 7, it was never a stable release but in some alpha. I still have few D7 sites which are using this module, that's the reason I'm asking here.

**Comment by mccrodp** [comment]
@rajibmp is right, there was a D7 version until the end 2016. There was an unresolved copyright disagreement around this version of the module, so it was best to remove the module and start afresh with D8 (you are right @NewZeal, you normally cannot delete, but in circumstances like this, you request via Webmaster queue). 

Sorry if this has caused you any issue @rajibmp, better for you to maintain the D7 version privately, if you still have it, to avoid any further complications.

**Comment by ghost** [comment]
No problem @mccrodp, sad to see the D7 module is not maintained in DO. 

I have a copy of it and some improvements on security, if you could give a hint what those unresolved copyright disagreement were then it'd be helpful. I was planning to make a github repo with added changes and make it publicly available if anyone wants to use it for D7. But would like to do without getting into legal troubles ;-)

**Comment by mccrodp** [comment]
I cannot talk about it in detail or give names due to an agreement. It stems from what I believe are cultural differences, on what constitutes ownership of something, developed outside of office hours. Anyway, it was agreed to remove it, so I would advise not making it available again. Of course, you have a copy, so nobody can stop your continued usage and improvement of that, privately.

Please feel free to contribute any of those improvements to the D8 version via PR, that would be greatly appreciated.
